# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_eyebrow', models.CharField(default='Selected Work', max_length=80)),
                ('intro_heading', models.CharField(default='Engineering Case Studies', max_length=160)),
                ('intro_text', models.TextField(default="A closer look at the systems I've designed, built, and shipped.")),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('badge_label', models.CharField(help_text="Human-readable badge shown on the card, e.g. 'Real-Time System'", max_length=80)),
                ('tech_stack_summary', models.CharField(help_text='e.g. Laravel • Vue • MySQL', max_length=120)),
                ('tech_chips', models.CharField(help_text='Comma-separated short chips, e.g. Laravel 10, MySQL Schema, REST API', max_length=200)),
                ('summary', wagtail.fields.RichTextField()),
                ('programming_language', models.CharField(help_text="Comma-separated, used for the SoftwareSourceCode JSON-LD, e.g. 'Python, Asyncio, WebSockets, Redis'", max_length=160)),
                ('featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(blank=True, help_text='Lower numbers appear first among featured projects on the homepage.', null=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 5), ('bullet_list', 6), ('diagram', 11)], blank=True, block_lookup={0: ('core.blocks.HeadingBlock', (), {}), 1: ('core.blocks.ParagraphBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('php', 'PHP'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('lua', 'Lua'), ('bash', 'Bash / Shell'), ('django', 'Django template'), ('json', 'JSON'), ('yaml', 'YAML')]}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('language', 2), ('filename', 3), ('code', 4)]], {}), 6: ('core.blocks.BulletListBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 7), ('sublabel', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('nodes', 10)]], {})})),
                ('categories', modelcluster.fields.ParentalManyToManyField(related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=120)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='projects.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
