# Generated by Django 5.2.17 on 2026-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='architecture_highlight',
            field=models.TextField(blank=True, default='', help_text="Home featured card callout. The 'Architecture highlight:' label is fixed in the template."),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='core_problem',
            field=models.CharField(blank=True, default='', help_text="Index card 'Core Problem:' line", max_length=200),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='role_label',
            field=models.CharField(blank=True, default='', help_text="Role shown on the home and index cards, e.g. 'Backend Architect'", max_length=80),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='solution',
            field=models.CharField(blank=True, default='', help_text="Index card 'Solution:' line", max_length=200),
        ),
    ]
