# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Soyal.dev', max_length=60)),
                ('tagline', models.CharField(default='Senior Backend Developer & Software Engineer', max_length=160)),
                ('footer_blurb', models.TextField(default='Backend-focused software engineer building reliable APIs, CMS platforms, and data-driven systems.')),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=120)),
                ('availability_status', models.CharField(default='Available for Senior Backend & Software Engineering Roles', max_length=160)),
                ('contact_email', models.EmailField(default='soyal@example.com', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com/')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/')),
                ('person_name', models.CharField(default='Soyal', max_length=80)),
                ('person_job_title', models.CharField(default='Senior Backend Developer & Software Engineer', max_length=160)),
                ('knows_about', models.CharField(default='Python, Django, FastAPI, PHP, Laravel, Wagtail CMS, REST APIs, MySQL, PostgreSQL, Database Design, API Security', help_text='Comma-separated list used in the homepage Person JSON-LD.', max_length=500)),
                ('org_name', models.CharField(default='Soyal Engineering Portfolio', max_length=160)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site brand settings',
            },
        ),
    ]
