# Generated by Django 5.2.17 on 2026-08-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebrandsettings',
            name='coordinates',
            field=models.CharField(default='27.7172° N, 85.3240° E', help_text='Right caption on the home hero portrait frame.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitebrandsettings',
            name='portrait',
            field=models.ForeignKey(blank=True, help_text='Editorial portrait used on the home hero and About sidebar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitebrandsettings',
            name='portrait_caption',
            field=models.CharField(default='soyal.portrait', help_text="Left caption in the portrait frame's header bar.", max_length=60),
        ),
        migrations.AddField(
            model_name='sitebrandsettings',
            name='timezone_label',
            field=models.CharField(default='UTC+5:45', max_length=30),
        ),
    ]
