# Generated by Django 5.2.17 on 2026-08-14 08:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='direct_heading',
            field=models.CharField(default='Direct Communication', max_length=80),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='direct_text',
            field=wagtail.fields.RichTextField(default='<p>I prefer direct, clear communication. I am based in Kathmandu, Nepal (UTC+5:45) and generally respond to all messages within 24 hours.</p>'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_eyebrow',
            field=models.CharField(default='Get In Touch', max_length=80),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='timezone_detail',
            field=models.CharField(default='Nepal Time (NPT, UTC+5:45) • Available for Remote Teams', max_length=160),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro_heading',
            field=models.CharField(default="Let's Talk Code & Projects", max_length=160),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(default='<p>Have a backend project idea, need Wagtail CMS integration, or want to discuss a senior engineering opportunity? Reach out directly or fill out the form below.</p>'),
        ),
    ]
