# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_eyebrow', models.CharField(default='Engineering Notes', max_length=80)),
                ('intro_heading', models.CharField(default='Backend & CMS Engineering Blog', max_length=160)),
                ('intro_text', models.TextField(default="Deep dives into the problems I've solved building APIs, CMS platforms, and data-driven systems.")),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category_label', models.CharField(help_text="Human-readable badge shown on the card, e.g. 'FastAPI & Async'", max_length=80)),
                ('excerpt', models.TextField(max_length=400)),
                ('date_published', models.DateField()),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 5), ('bullet_list', 6), ('diagram', 11)], blank=True, block_lookup={0: ('core.blocks.HeadingBlock', (), {}), 1: ('core.blocks.ParagraphBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('php', 'PHP'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('lua', 'Lua'), ('bash', 'Bash / Shell'), ('django', 'Django template'), ('json', 'JSON'), ('yaml', 'YAML')]}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('language', 2), ('filename', 3), ('code', 4)]], {}), 6: ('core.blocks.BulletListBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 7), ('sublabel', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('nodes', 10)]], {})})),
                ('categories', modelcluster.fields.ParentalManyToManyField(related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpostpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
