# Generated by Django 5.2.17 on 2026-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='show_toc',
            field=models.BooleanField(default=False, help_text='Show the sticky table of contents sidebar (long guides only).'),
        ),
    ]
