# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
import home.models
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_cta_heading',
            field=models.CharField(default='Have a problem worth solving?', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_cta_text',
            field=wagtail.fields.RichTextField(default="<p>I'm always interested in hearing about new projects and opportunities.</p>"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_eyebrow',
            field=models.CharField(default='Case Studies', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_heading',
            field=models.CharField(default='Featured Engineering Projects', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_intro',
            field=models.TextField(default="A selection of production systems I've designed and built end to end."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading_highlight',
            field=models.CharField(default='reliable APIs', help_text='Substring of the heading above to render with the gradient accent.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading_main',
            field=models.CharField(default='Building software that ships reliable APIs.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subhead',
            field=models.TextField(default='Senior backend developer specializing in Python, Django, Wagtail CMS, and Laravel — designing systems that scale from single-store POS platforms to enterprise content management.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='philosophy_eyebrow',
            field=models.CharField(default='Engineering Philosophy', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='philosophy_heading',
            field=models.CharField(default='How I Build Software', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='philosophy_intro',
            field=models.TextField(default='Three principles that guide every system I design.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_pills',
            field=models.CharField(default='Python, Django, FastAPI, Laravel, Wagtail CMS, MySQL/PostgreSQL, REST APIs', help_text="Comma-separated list rendered as the 'Core Stack Expertise' pills.", max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='terminal_json',
            field=models.JSONField(default=dict, help_text='Fake-terminal hero card content. Shape: {"identity": {"name", "role", "location", "status"}, "services": ["...", ...], "metrics": {"uptime", "latency", "note"}}', validators=[home.models.validate_terminal_json]),
        ),
        migrations.CreateModel(
            name='HomePagePhilosophyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(help_text='e.g. 01', max_length=4)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='philosophy_steps', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
