# Generated by Django 5.2.17 on 2026-08-14 08:37

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_contact_cta_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_projects_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skill_pills',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='terminal_json',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_label',
            field=models.CharField(default='Send Me a Message', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_eyebrow',
            field=models.CharField(default="Let's Build Together", max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_footnote',
            field=models.CharField(default='Based in Kathmandu, Nepal (UTC+5:45) • Usually responding within 24 hours.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_eyebrow',
            field=models.CharField(default='Core Expertise', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_heading',
            field=models.CharField(default='Backend Engineering & System Architecture', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_intro',
            field=models.TextField(default='Here is how I help engineering teams and businesses build fast, secure, and maintainable software.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_link_text',
            field=models.CharField(default='View all projects catalog →', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_ghost_label',
            field=models.CharField(default='CV / Resume', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_label',
            field=models.CharField(default='View Selected Work', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_label',
            field=models.CharField(default="Let's Talk", max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='interests_eyebrow',
            field=models.CharField(default='Beyond The Terminal', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='interests_heading',
            field=models.CharField(default='Life Outside The Terminal', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='interests_lede',
            field=models.TextField(default='Great software is built by real people with broad perspectives and clear minds.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portrait_caption_line',
            field=models.CharField(default='Specializing in Wagtail CMS, Django, FastAPI & Laravel', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portrait_role_chip',
            field=models.CharField(default='Backend Architect', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='snapshot_eyebrow',
            field=models.CharField(default='Developer Snapshot', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='snapshot_note',
            field=models.CharField(default='Fast Facts & Environment', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='status_eyebrow',
            field=models.CharField(default='Live Status', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='status_heading',
            field=models.CharField(default='Currently Building & Exploring', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='status_updated_label',
            field=models.CharField(default='Updated August 2026', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_body',
            field=wagtail.fields.RichTextField(default='<p>My journey into software engineering started in Kathmandu with a simple fascination: how can code reliably coordinate inventory, money, and content across distributed users without falling apart? That curiosity drove me straight to backend systems, database transactions, and content architectures.</p><p>Over the years, I have architected and deployed production backends ranging from multi-outlet POS billing engines to headless e-commerce platforms and high-concurrency ticket locking systems. I specialize particularly in <strong>Wagtail CMS & Django</strong> because it provides the sweet spot of structured, flexible StreamField content authoring with the raw power and security of Python.</p>'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_callout_heading',
            field=models.CharField(default='What Drives My Work Daily:', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_eyebrow',
            field=models.CharField(default='About Soyal', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_heading',
            field=models.CharField(default='Engineering systems that are explicit, secure, and built to last.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_lede',
            field=models.TextField(default='I am a backend developer who cares deeply about schema integrity, clean domain boundaries, and creating interfaces that editorial teams actually enjoy using.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='story_link_text',
            field=models.CharField(default='Read my full journey and story →', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='terminal_filename',
            field=models.CharField(default='soyal_env.json', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='toolbox_eyebrow',
            field=models.CharField(default='My Toolbox', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='toolbox_heading',
            field=models.CharField(default='Technologies & Daily Drivers', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='toolbox_note',
            field=models.CharField(default='Every tool here is used in production systems.', max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_cta_heading',
            field=models.CharField(default='Have an interesting backend challenge or Wagtail project?', max_length=160),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_cta_text',
            field=wagtail.fields.RichTextField(default='<p>I am always interested in discussing senior backend engineering roles, Wagtail CMS architecture, and challenging database problems.</p>'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_projects_eyebrow',
            field=models.CharField(default='Production Work', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_projects_heading',
            field=models.CharField(default='Featured Engineering Case Studies', max_length=160),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading_highlight',
            field=models.CharField(default='Soyal', help_text='Substring of the heading above to render with the accent color.', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading_main',
            field=models.CharField(default="Hi, I'm Soyal.", max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subhead',
            field=wagtail.fields.RichTextField(default='<p>I design and build production-grade web applications, high-concurrency APIs, resilient database architectures, and bespoke CMS platforms using <strong>Python (Django, Wagtail, FastAPI)</strong> and <strong>PHP (Laravel)</strong>.</p>'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='philosophy_eyebrow',
            field=models.CharField(default='Engineering Principles', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='philosophy_heading',
            field=models.CharField(default='How I Think & Build Software', max_length=160),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='philosophy_intro',
            field=models.TextField(default='The guiding rules I follow when architecting systems for production stability and maintainability.'),
        ),
        migrations.CreateModel(
            name='HomePageExpertisePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('ordinal_label', models.CharField(help_text='e.g. 01 / APIS & CONCURRENCY', max_length=40)),
                ('stack_badge', models.CharField(help_text='e.g. FastAPI • Django REST', max_length=60)),
                ('heading', models.CharField(max_length=120)),
                ('description', wagtail.fields.RichTextField()),
                ('chips', models.CharField(help_text='Comma-separated', max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_pillars', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('emoji', models.CharField(max_length=8)),
                ('label', models.CharField(max_length=60)),
                ('heading', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageSnapshotFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=60)),
                ('sub_value', models.CharField(max_length=60)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_facts', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageStatusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('emoji', models.CharField(max_length=8)),
                ('category_label', models.CharField(max_length=40)),
                ('accent', models.CharField(choices=[('emerald', 'Emerald'), ('amber', 'Amber'), ('teal', 'Teal'), ('purple', 'Purple')], default='emerald', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageStoryBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_bullets', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageTerminalRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=160)),
                ('accent', models.CharField(choices=[('emerald', 'Emerald'), ('amber', 'Amber'), ('teal', 'Teal'), ('purple', 'Purple')], default='emerald', max_length=10)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_rows', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageToolboxRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(help_text='Rows sharing a category render as one card; keep them adjacent.', max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('qualifier', models.CharField(max_length=40)),
                ('highlight', models.BooleanField(default=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_rows', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
