# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_heading', models.CharField(default='Engineering robust backend platforms with business clarity.', max_length=200)),
                ('intro_text', wagtail.fields.RichTextField(default='<p>An overview of my background, focus, and engineering mindset.</p>')),
                ('bio_heading', models.CharField(default='Professional Background & Value', max_length=160)),
                ('bio_paragraph_1', wagtail.fields.RichTextField()),
                ('bio_paragraph_2', wagtail.fields.RichTextField()),
                ('mindset_heading', models.CharField(default='Engineering Mindset', max_length=160)),
                ('mindset_text', wagtail.fields.RichTextField()),
                ('quick_facts_heading', models.CharField(default='Quick Facts', max_length=80)),
                ('capabilities_eyebrow', models.CharField(default='Technical Skill Inventory', max_length=80)),
                ('capabilities_heading', models.CharField(default='Technologies & Capabilities', max_length=160)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPageChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=160)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageQuickFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=160)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_facts', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageSkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge', models.CharField(help_text='e.g. BE, DB, CMS', max_length=4)),
                ('title', models.CharField(max_length=120)),
                ('items', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
