# Generated by Django 5.2.17 on 2026-08-14 08:37

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='bio_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bio_paragraph_1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bio_paragraph_2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mindset_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mindset_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='quick_facts_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpageskillcategory',
            name='items',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='intro_eyebrow',
            field=models.CharField(default='About Soyal', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='principles_heading',
            field=models.CharField(default='# Engineering Principles I Stand By', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='snapshot_cta_label',
            field=models.CharField(default="Let's Connect →", max_length=40),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='workspace_heading',
            field=models.CharField(default='Workspace & Tooling', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpagequickfact',
            name='accent',
            field=models.BooleanField(default=False, help_text='Renders this value in emerald (used for Availability).'),
        ),
        migrations.AddField(
            model_name='aboutpageskillcategory',
            name='chips',
            field=models.CharField(blank=True, default='', help_text='Comma-separated badge chips', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpageskillcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capabilities_eyebrow',
            field=models.CharField(default='Technical Inventory', max_length=80),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='capabilities_heading',
            field=models.CharField(default='What I Bring to an Engineering Team', max_length=160),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_heading',
            field=models.CharField(default='Developer background, engineering perspective & daily drivers.', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(default="<p>I'm a senior backend software developer based in Kathmandu, Nepal. I specialize in designing scalable database architectures, resilient REST APIs, and bespoke content management platforms using Python, Django, Wagtail CMS, and Laravel.</p>"),
        ),
        migrations.AlterField(
            model_name='aboutpagechecklistitem',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpageskillcategory',
            name='badge',
            field=models.CharField(help_text='e.g. 01', max_length=4),
        ),
        migrations.CreateModel(
            name='AboutPageNarrativeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=160)),
                ('body', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_blocks', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageWorkspaceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=120)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_rows', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
