# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_heading', models.CharField(default='Professional Experience', max_length=160)),
                ('intro_text', models.TextField(default="A timeline of roles, responsibilities, and the systems I've built along the way.")),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role_title', models.CharField(max_length=160)),
                ('company_name', models.CharField(max_length=160)),
                ('date_range', models.CharField(help_text='e.g. 2023 — Present', max_length=80)),
                ('location', models.CharField(help_text='e.g. Kathmandu, Nepal (Remote)', max_length=160)),
                ('is_current', models.BooleanField(default=False, help_text='Highlights this entry in emerald as the current role.')),
                ('bullet_points', models.TextField(help_text='One responsibility per line — rendered as a bullet list.')),
                ('tech_tags', models.CharField(blank=True, help_text='Comma-separated, e.g. Python, Django, Wagtail, FastAPI, PostgreSQL', max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='experience.experiencepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
