# Generated by Django 5.2.17 on 2026-08-13 05:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('full_name', models.CharField(default='Soyal', max_length=120)),
                ('tagline', models.CharField(default='Senior Backend Developer & Software Engineer', max_length=160)),
                ('contact_line', models.CharField(default='Kathmandu, Nepal · soyal@example.com', help_text='Rendered under the name/tagline, e.g. location and email.', max_length=200)),
                ('professional_summary', wagtail.fields.RichTextField()),
                ('education_line', models.CharField(help_text='e.g. B.Sc. Computer Science — Tribhuvan University, Kathmandu', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResumeExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Role — Company', max_length=160)),
                ('date_range', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=160)),
                ('bullet_points', models.TextField(help_text='One condensed bullet per line.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='resume.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_highlights', to='resume.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeSkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='e.g. Languages & Frameworks', max_length=60)),
                ('values', models.CharField(help_text='Comma-separated skill list', max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='resume.resumepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
