# Generated by Django 5.2.17 on 2026-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='education_location',
            field=models.CharField(default='Kathmandu, Nepal', max_length=120),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='education_line',
            field=models.CharField(help_text='Degree only, e.g. Bachelor of Science in Computer Science & Information Technology (BSc.CSIT)', max_length=200),
        ),
    ]
